-- Secure code-based sync for Business English Hub.
-- Run in Supabase SQL Editor for project ahqeqgovcwgslxwlnwsl.
--
-- Model:
-- - Users do not log in with email.
-- - A progress code, e.g. swift-48291, restores low-risk learning progress.
-- - Direct public table access is blocked by RLS + revoked privileges.
-- - Browser clients use SECURITY DEFINER RPC functions instead.
-- - Anyone who knows a progress code can restore that progress. Do not store personal data.

create table if not exists public.user_progress (
  user_code text primary key,
  completed_exercises jsonb not null default '{}'::jsonb,
  dual_coding jsonb not null default '{}'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  flashcard_positions jsonb not null default '{}'::jsonb,
  streak_current integer not null default 0,
  streak_best integer not null default 0,
  streak_last_date date,
  total_reviews integer not null default 0,
  total_correct integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.card_reviews (
  user_code text not null,
  card_id text not null,
  deck text,
  ease_factor numeric not null default 2.5,
  interval_days integer not null default 1,
  repetitions integer not null default 0,
  next_review date,
  last_reviewed timestamptz,
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  again_count integer not null default 0,
  primary key (user_code, card_id)
);

create table if not exists public.session_log (
  id bigint generated by default as identity primary key,
  user_code text,
  exercise_type text,
  deck text,
  cards_reviewed integer not null default 0,
  cards_correct integer not null default 0,
  duration_sec integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.user_progress enable row level security;
alter table public.card_reviews enable row level security;
alter table public.session_log enable row level security;

revoke all on public.user_progress from anon, authenticated;
revoke all on public.card_reviews from anon, authenticated;
revoke all on public.session_log from anon, authenticated;
revoke all on sequence public.session_log_id_seq from anon, authenticated;

create or replace function public.be4w_valid_user_code(p_user_code text)
returns boolean
language sql
immutable
as $$
  select p_user_code ~ '^[a-z]+-[0-9]{4,5}$'
$$;

create or replace function public.be4w_get_user_progress(p_user_code text)
returns table (
  user_code text,
  completed_exercises jsonb,
  dual_coding jsonb,
  settings jsonb,
  flashcard_positions jsonb,
  streak_current integer,
  streak_best integer,
  streak_last_date date,
  total_reviews integer,
  total_correct integer,
  updated_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select up.user_code, up.completed_exercises, up.dual_coding, up.settings,
         up.flashcard_positions, up.streak_current, up.streak_best,
         up.streak_last_date, up.total_reviews, up.total_correct, up.updated_at
  from public.user_progress up
  where public.be4w_valid_user_code(p_user_code)
    and up.user_code = lower(trim(p_user_code));
$$;

create or replace function public.be4w_upsert_user_progress(
  p_user_code text,
  p_completed_exercises jsonb,
  p_dual_coding jsonb,
  p_settings jsonb,
  p_flashcard_positions jsonb,
  p_streak_current integer,
  p_streak_best integer,
  p_streak_last_date date,
  p_total_reviews integer,
  p_total_correct integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.be4w_valid_user_code(p_user_code) then
    raise exception 'Invalid progress code';
  end if;

  insert into public.user_progress (
    user_code, completed_exercises, dual_coding, settings, flashcard_positions,
    streak_current, streak_best, streak_last_date, total_reviews, total_correct, updated_at
  ) values (
    lower(trim(p_user_code)), coalesce(p_completed_exercises, '{}'::jsonb),
    coalesce(p_dual_coding, '{}'::jsonb), coalesce(p_settings, '{}'::jsonb),
    coalesce(p_flashcard_positions, '{}'::jsonb), coalesce(p_streak_current, 0),
    coalesce(p_streak_best, 0), p_streak_last_date, coalesce(p_total_reviews, 0),
    coalesce(p_total_correct, 0), now()
  )
  on conflict (user_code) do update set
    completed_exercises = excluded.completed_exercises,
    dual_coding = excluded.dual_coding,
    settings = excluded.settings,
    flashcard_positions = excluded.flashcard_positions,
    streak_current = excluded.streak_current,
    streak_best = excluded.streak_best,
    streak_last_date = excluded.streak_last_date,
    total_reviews = excluded.total_reviews,
    total_correct = excluded.total_correct,
    updated_at = now();
end;
$$;

create or replace function public.be4w_get_card_reviews(p_user_code text)
returns table (
  user_code text,
  card_id text,
  deck text,
  ease_factor numeric,
  interval_days integer,
  repetitions integer,
  next_review date,
  last_reviewed timestamptz,
  correct_count integer,
  wrong_count integer,
  again_count integer
)
language sql
security definer
set search_path = public
as $$
  select cr.user_code, cr.card_id, cr.deck, cr.ease_factor, cr.interval_days,
         cr.repetitions, cr.next_review, cr.last_reviewed, cr.correct_count,
         cr.wrong_count, cr.again_count
  from public.card_reviews cr
  where public.be4w_valid_user_code(p_user_code)
    and cr.user_code = lower(trim(p_user_code));
$$;

create or replace function public.be4w_upsert_card_review(
  p_user_code text,
  p_card_id text,
  p_deck text,
  p_ease_factor numeric,
  p_interval_days integer,
  p_repetitions integer,
  p_next_review date,
  p_last_reviewed timestamptz,
  p_correct_count integer,
  p_wrong_count integer,
  p_again_count integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.be4w_valid_user_code(p_user_code) then
    raise exception 'Invalid progress code';
  end if;
  if p_card_id is null or length(trim(p_card_id)) = 0 then
    raise exception 'Invalid card id';
  end if;

  insert into public.card_reviews (
    user_code, card_id, deck, ease_factor, interval_days, repetitions,
    next_review, last_reviewed, correct_count, wrong_count, again_count
  ) values (
    lower(trim(p_user_code)), p_card_id, p_deck, coalesce(p_ease_factor, 2.5),
    coalesce(p_interval_days, 1), coalesce(p_repetitions, 0), p_next_review,
    p_last_reviewed, coalesce(p_correct_count, 0), coalesce(p_wrong_count, 0),
    coalesce(p_again_count, 0)
  )
  on conflict (user_code, card_id) do update set
    deck = excluded.deck,
    ease_factor = excluded.ease_factor,
    interval_days = excluded.interval_days,
    repetitions = excluded.repetitions,
    next_review = excluded.next_review,
    last_reviewed = excluded.last_reviewed,
    correct_count = excluded.correct_count,
    wrong_count = excluded.wrong_count,
    again_count = excluded.again_count;
end;
$$;

create or replace function public.be4w_log_session(
  p_user_code text,
  p_exercise_type text,
  p_deck text,
  p_cards_reviewed integer,
  p_cards_correct integer,
  p_duration_sec integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_user_code is not null and not public.be4w_valid_user_code(p_user_code) then
    raise exception 'Invalid progress code';
  end if;

  insert into public.session_log (
    user_code, exercise_type, deck, cards_reviewed, cards_correct, duration_sec
  ) values (
    lower(trim(p_user_code)), p_exercise_type, p_deck, coalesce(p_cards_reviewed, 0),
    coalesce(p_cards_correct, 0), coalesce(p_duration_sec, 0)
  );
end;
$$;

grant execute on function public.be4w_get_user_progress(text) to anon, authenticated;
grant execute on function public.be4w_upsert_user_progress(text, jsonb, jsonb, jsonb, jsonb, integer, integer, date, integer, integer) to anon, authenticated;
grant execute on function public.be4w_get_card_reviews(text) to anon, authenticated;
grant execute on function public.be4w_upsert_card_review(text, text, text, numeric, integer, integer, date, timestamptz, integer, integer, integer) to anon, authenticated;
grant execute on function public.be4w_log_session(text, text, text, integer, integer, integer) to anon, authenticated;

-- Verify RLS is enabled.
select schemaname, tablename, rowsecurity
from pg_tables
where schemaname = 'public'
order by tablename;
